[Lacros_Lim]
    location = "Limassol"
    shortname = "Lim"
    loader = "mira"
[Lacros_Lim.settings]
    decoupling = -30
    grid_time = 6
    max_no_nodes = 15
    LDR = true
    #roll_velocity = 65 # for 512 bins = 7.92 m/s
    roll_velocity = 98 # = 6.56 m/s
    station_altitude = 12
    #add_to_fname = '_rectwin'
[Lacros_Lim.settings.peak_finding_params]
    #vel_smooth = [0.2,0.2,0.2,0.2,0.2]
    #vel_smooth = [0.33,0.33,0.33]
    thres_factor_co = 4.0 # false | factor in linear units
    thres_factor_cx = 2.0 # false | factor in linear units
    span = 0.1
    smooth_polyorder = 1


[Lacros_at_ACCEPT]
    location = "Cabauw"
    shortname = "Cab"
[Lacros_at_ACCEPT.settings]
    decoupling = -30
    #grid_time = 4
    #grid_time = 6
    grid_time = 10
    max_no_nodes = 15
    LDR = true
    station_altitude = -1
[Lacros_at_ACCEPT.settings.peak_finding_params]
    thres_factor_co = 2.0 # false | factor in linear units
    thres_factor_cx = 2.0 # false | factor in linear units
    span = 0.1
    smooth_polyorder = 1

[Lacros_Pun]
    location = "Punta Arenas"
    shortname = "Pun"
    loader = "mira"
[Lacros_Pun.settings]
    decoupling = -30
    grid_time = 6
    max_no_nodes = 15
    polarimetry = 'LDR'
    smooth_cut_sequence = 'sc' # cs cut-smooth | sc smooth-cut
    #roll_velocity = 65 # for 512 bins = 7.92 m/s
    roll_velocity = 98 # = 6.56 m/s
    station_altitude = 9
    #add_to_fname = '_rectwin'
[Lacros_Pun.settings.peak_finding_params]
    # supress spurious peaks introduced by tails; back to 3 as the other tail filter should work better
    thres_factor_co = 2.5 # false | factor in linear units
    thres_factor_cx = 2.0 # false | factor in linear units
    cal_offset = 0        # dB
    tail_filter = true    # true | false | omit; only tested with LACROS-Mira 
    # new: seconds instead of index
    t_avg = 5             # s
    h_avg = 0             # m
    span = 0.3            # m s-1
    smooth_polyorder = 2  # 0 deactivate | 2 second order
    prom_thres = 0.5      # dB
    width_thres = 0.05    # m s-1


[Polarstern]
    location = "Polarstern"
    shortname = "Pol"
[Polarstern.settings]
    decoupling = -27
    smooth = true
    #grid_time = 10
    max_no_nodes = 15
    thres_factor_co = 2.0 # false | factor in linear units
    thres_factor_cx = 2.0 # false | factor in linear units
    LDR = true
    station_altitude = 12

[Lindenberg]
    location = "Lindenberg"
    shortname = "Lin"
[Lindenberg.settings]
    decoupling = -25
    smooth = true
    #grid_time = false
    max_no_nodes = 15
    thres_factor_co = 2.0 # false | factor in linear units
    thres_factor_cx = 2.0 # false | factor in linear units
    LDR = true
    station_altitude = 100

[Davos]
    location = "Davos"
    shortname = "Dav"
[Davos.settings]
    decoupling = -25
    #grid_time = false
    max_no_nodes = 15
    LDR = true
    station_altitude = 1627
[Davos.settings.peak_finding_params]
    vel_smooth = true
    thres_factor_co = 4.0 # false | factor in linear units
    thres_factor_cx = 2.0 # false | factor in linear units

[kazr_baecc] 
    location = "Hyytiala" 
    shortname = "kazrbaecc" 
    loader = 'kazr_legacy'
[kazr_baecc.settings] 
    #grid_time = 6 
    max_no_nodes = 15 
    LDR = false 
    station_altitude = 181
[kazr_baecc.settings.peak_finding_params]
    #vel_smooth = true
    # original setting from the v0.2 relase
    vel_smooth = [0.14705882, 0.20588235, 0.29411765, 0.20588235, 0.14705882]
    thres_factor_co = 2.0 # false | factor in linear units
    thres_factor_cx = 2.0 # false | factor in linear units

[kazr_mosaic] 
    location = "MOSAiC" 
    shortname = "kazrmosaic" 
    loader = 'kazr_new'
[kazr_mosaic.settings] 
    #grid_time = 6 
    max_no_nodes = 15 
    LDR = false 
    station_altitude = 22
[kazr_mosaic.settings.peak_finding_params]
    #vel_smooth = true
    vel_smooth = [0.14705882, 0.20588235, 0.29411765, 0.20588235, 0.14705882]
    thres_factor_co = 2.0 # false | factor in linear units
    thres_factor_cx = 2.0 # false | factor in linear units

[mwacr_mosaic] 
    location = "MOSAiC" 
    shortname = "mwacrmosaic" 
    loader = 'kazr_new'
[mwacr_mosaic.settings] 
    #grid_time = 5 
    max_no_nodes = 15 
    LDR = false 
    station_altitude = 22
[mwacr_mosaic.settings.peak_finding_params]
    #vel_smooth = true
    vel_smooth = [0.14705882, 0.20588235, 0.29411765, 0.20588235, 0.14705882]
    thres_factor_co = 2.0 # false | factor in linear units
    thres_factor_cx = 2.0 # false | factor in linear units
    prom_thres = 0.5 # = 1.0 if omitted

[kazr_md_mosaic] 
    location = "MOSAiC" 
    shortname = "kazrmdmosaic" 
    loader = 'kazr_new'
[kazr_md_mosaic.settings] 
    #grid_time = 6 
    max_no_nodes = 15 
    LDR = false 
    station_altitude = 22
[kazr_md_mosaic.settings.peak_finding_params]
    #vel_smooth = true
    vel_smooth = [0.14705882, 0.20588235, 0.29411765, 0.20588235, 0.14705882]
    thres_factor_co = 2.0 # false | factor in linear units
    thres_factor_cx = 2.0 # false | factor in linear units

[joyrad_nya] 
    location = "Ny-Alesund" 
    shortname = "joyrad_nya" 
[joyrad_nya.settings] 
    #smooth = true 
    smooth = 'broad' 
    #grid_time = 4 
    max_no_nodes = 15 
    # for joyrad test linear factor
    #thres_factor_cx = 3.0 
    thres_factor_co = 1.5 # false | factor in linear units
    LDR = false 
    station_altitude = 10


[limrad_peako] 
    location = "Leipzig"
    shortname = "Lei"
    loader = 'rpgpy'
[limrad_peako.settings] 
    grid_time = false
    max_no_nodes = 15 
    #LDR = true 
    polarimetry = 'STSR' 
    tot_spec_scaling = 4
    smooth_cut_sequence = 'sc' # cs cut-smooth | sc smooth-cut
    decoupling = -30
    station_altitude = 100
# chirps in zero-based indexing
[limrad_peako.settings.peak_finding_params.chirp0]
    # new: seconds instead of index
    t_avg = 0            # s
    h_avg = 89          # m
    span = 0.2          # m s-1
    smooth_polyorder = 2
    prom_thres = 0.5     # dB
    width_thres = 0      # m s-1
[limrad_peako.settings.peak_finding_params.chirp1]
    t_avg = 9           # s
    h_avg = 0            # m
    span = 0.05           # m s-1
    smooth_polyorder = 2
    prom_thres = 0.5     # dB
    width_thres = 0      # m s-1
[limrad_peako.settings.peak_finding_params.chirp2]
    t_avg = 0            # s
    h_avg = 0            # m
    span = 0.2           # m s-1
    smooth_polyorder = 2
    prom_thres = 0.0     # dB
    width_thres = 0      # m s-1

[limrad_punta] 
    location = "Punta Arenas"
    shortname = "Pun"
    loader = 'rpgpy'
[limrad_punta.settings] 
    grid_time = false
    max_no_nodes = 15 
    tot_spec_scaling = 2
    polarimetry = 'STSR' 
    smooth_cut_sequence = 'sc' # cs cut-smooth | sc smooth-cut
    decoupling = -30
    station_altitude = 22
[limrad_punta.settings.peak_finding_params.chirp0]
    thres_factor_co = false # false | factor in linear units
    # new: seconds instead of index
    t_avg = 0            # s
    h_avg = 89          # m
    span = 0.2          # m s-1
    smooth_polyorder = 2
    prom_thres = 0.5     # dB
    width_thres = 0      # m s-1
[limrad_punta.settings.peak_finding_params.chirp1]
    thres_factor_co = false # false | factor in linear units
    t_avg = 9           # s
    h_avg = 0            # m
    span = 0.05           # m s-1
    smooth_polyorder = 2
    prom_thres = 0.5     # dB
    width_thres = 0      # m s-1
[limrad_punta.settings.peak_finding_params.chirp2]
    thres_factor_co = false # false | factor in linear units
    t_avg = 0            # s
    h_avg = 0            # m
    span = 0.2           # m s-1
    smooth_polyorder = 2
    prom_thres = 0.0     # dB
    width_thres = 0      # m s-1
