[Lacros_Lim]
    location = "Limassol"
    shortname = "Lim"
    loader = "mira"
[Lacros_Lim.settings]
    decoupling = -30
    grid_time = 6
    max_no_nodes = 15
    LDR = true
    #roll_velocity = 65 # for 512 bins = 7.92 m/s
    roll_velocity = 98 # = 6.56 m/s
    station_altitude = 12
    #add_to_fname = '_rectwin'
[Lacros_Lim.settings.peak_finding_params]
    #vel_smooth = [0.2,0.2,0.2,0.2,0.2]
    #vel_smooth = [0.33,0.33,0.33]
    thres_factor_co = 6.0 # supress spurious peaks introduced by tails
    thres_factor_cx = 3.0
    span = 0.1
    smooth_polyorder = 1


[Lacros_at_ACCEPT]
    location = "Cabauw"
    shortname = "Cab"
[Lacros_at_ACCEPT.settings]
    decoupling = -30
    #grid_time = 4
    #grid_time = 6
    grid_time = 10
    max_no_nodes = 15
    LDR = true
    station_altitude = -1
[Lacros_at_ACCEPT.settings.peak_finding_params]
    thres_factor_co = 3.0 # supress spurious peaks introduced by tails
    thres_factor_cx = 3.0
    span = 0.1
    smooth_polyorder = 1

[Lacros_Pun]
    location = "Punta Arenas"
    shortname = "Pun"
    loader = "mira"
[Lacros_Pun.settings]
    decoupling = -30
    grid_time = 6
    max_no_nodes = 15
    LDR = true
    #roll_velocity = 65 # for 512 bins = 7.92 m/s
    roll_velocity = 98 # = 6.56 m/s
    station_altitude = 9
    #add_to_fname = '_rectwin'
[Lacros_Pun.settings.peak_finding_params]
    #vel_smooth = [0.2,0.2,0.2,0.2,0.2]
    #vel_smooth = [0.33,0.33,0.33]
    thres_factor_co = 6.0 # supress spurious peaks introduced by tails
    thres_factor_cx = 3.0
    span = 0.1
    smooth_polyorder = 1


[Polarstern]
    location = "Polarstern"
    shortname = "Pol"
[Polarstern.settings]
    decoupling = -27
    smooth = true
    grid_time = 10
    max_no_nodes = 15
    thres_factor_co = 3.0
    thres_factor_cx = 3.0
    LDR = true
    station_altitude = 12

[Lindenberg]
    location = "Lindenberg"
    shortname = "Lin"
[Lindenberg.settings]
    decoupling = -25
    smooth = true
    grid_time = false
    max_no_nodes = 15
    thres_factor_co = 3.0
    thres_factor_cx = 3.0
    LDR = true
    station_altitude = 100

[Davos]
    location = "Davos"
    shortname = "Dav"
[Davos.settings]
    decoupling = -25
    grid_time = false
    max_no_nodes = 15
    LDR = true
    station_altitude = 1627
[Davos.settings.peak_finding_params]
    vel_smooth = true
    thres_factor_co = 6.0 # supress spurious peaks introduced by tails
    thres_factor_cx = 3.0

[kazr_baecc] 
    location = "Hyytiala" 
    shortname = "kazrbaecc" 
    loader = 'kazr_legacy'
[kazr_baecc.settings] 
    grid_time = 6 
    max_no_nodes = 15 
    LDR = false 
    station_altitude = 181
[kazr_baecc.settings.peak_finding_params]
    #vel_smooth = true
    # original setting from the v0.2 relase
    vel_smooth = [0.14705882, 0.20588235, 0.29411765, 0.20588235, 0.14705882]
    thres_factor_co = 3.0 
    thres_factor_cx = 3.0

[kazr_mosaic] 
    location = "MOSAiC" 
    shortname = "kazrmosaic" 
    loader = 'kazr_new'
[kazr_mosaic.settings] 
    grid_time = 6 
    max_no_nodes = 15 
    LDR = false 
    station_altitude = 22
[kazr_mosaic.settings.peak_finding_params]
    #vel_smooth = true
    vel_smooth = [0.14705882, 0.20588235, 0.29411765, 0.20588235, 0.14705882]
    thres_factor_co = 3.0 
    thres_factor_cx = 3.0

[mwacr_mosaic] 
    location = "MOSAiC" 
    shortname = "mwacrmosaic" 
    loader = 'kazr_new'
[mwacr_mosaic.settings] 
    grid_time = 5 
    max_no_nodes = 15 
    LDR = false 
    station_altitude = 22
[mwacr_mosaic.settings.peak_finding_params]
    #vel_smooth = true
    vel_smooth = [0.14705882, 0.20588235, 0.29411765, 0.20588235, 0.14705882]
    thres_factor_co = 3.0 
    thres_factor_cx = 3.0
    prom_thres = 0.5 # = 1.0 if omitted

[kazr_md_mosaic] 
    location = "MOSAiC" 
    shortname = "kazrmdmosaic" 
    loader = 'kazr_new'
[kazr_md_mosaic.settings] 
    grid_time = 6 
    max_no_nodes = 15 
    LDR = false 
    station_altitude = 22
[kazr_md_mosaic.settings.peak_finding_params]
    #vel_smooth = true
    vel_smooth = [0.14705882, 0.20588235, 0.29411765, 0.20588235, 0.14705882]
    thres_factor_co = 3.0 
    thres_factor_cx = 3.0

[joyrad_nya] 
    location = "Ny-Alesund" 
    shortname = "joyrad_nya" 
[joyrad_nya.settings] 
    #smooth = true 
    smooth = 'broad' 
    grid_time = 4 
    max_no_nodes = 15 
    # for joyrad test linear factor
    thres_factor_co = 2 
    #thres_factor_cx = 3.0 
    LDR = false 
    station_altitude = 10


[limrad_peako] 
    location = "Punta Arenas"
    shortname = "Pun"
[limrad_peako.settings] 
    grid_time = false
    max_no_nodes = 15 
    LDR = true 
    decoupling = -35
    station_altitude = 22
[limrad_peako.settings.peak_finding_params]
    t_avg = 4
    h_avg = 1
    span = 0.5
    smooth_polyorder = 1
    prom_thres = 1
    width_thres = 3
